Repository AdaSupport/embed, pull requests merged in 2019-10, with the labels that each got.

#145 EM-87: Add Embed identifer
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/XS

#146 Merge beta in master
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/S

#144 BUIL-144: Receive message to reset chat
  src/components/AppWrapper/App/index.tsx
Labels: size/S

#148 Merge beta in master (#146)
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/S

#147 BUIL-144: Receive message to reset chat
  src/components/AppWrapper/App/index.tsx
Labels: size/M
