Repository AdaSupport/embed, pull requests merged in 2019-03, with the labels that each got.

#63 Set Node version to 11.10
  .circleci/config.yml
Labels: size/XS

#65 FND-958, FND-959: Bug Fixes
  src/components/App/index.tsx
  src/components/App/style.scss
  src/index.ejs
Labels: size/S

#67 HOTFIX: Remove height 100%
  src/components/App/style.scss
Labels: size/XS

#68 HOTFIX: Remove height 100%
  src/components/App/style.scss
Labels: size/XS

#70 FND-966: Fix for parent element height
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/components/App/style.scss
  src/index.ejs
Labels: size/M

#71 FND-966: Fix for parent element height
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/components/App/style.scss
  src/index.ejs
Labels: size/M

#62 FND-915: Add Sentry Logging
  .env.example
  package.json
  parent.config.js
  src/components/App/index.tsx
  src/index.ts
  src/services/checkRollout.ts
  src/services/errorTracker.js
  yarn.lock
Labels: size/M

#72 FND-915: Add Sentry Logging
  .env.example
  package.json
  parent.config.js
  src/components/App/index.tsx
  src/index.ts
  src/services/checkRollout.ts
  src/services/errorTracker.js
  yarn.lock
Labels: size/M

#73 FND-915: Whitelist URL in Sentry
  src/index.ts
Labels: size/XS

#74 FND-915: Whitelist URL in Sentry
  .env.example
  package.json
  parent.config.js
  src/components/App/index.tsx
  src/index.ts
  src/services/checkRollout.ts
  src/services/errorTracker.js
  yarn.lock
Labels: size/L

#75 Revert "FND-915: Whitelist URL in Sentry"
  .env.example
  package.json
  parent.config.js
  src/components/App/index.tsx
  src/index.ts
  src/services/checkRollout.ts
  src/services/errorTracker.js
  yarn.lock
Labels: size/L

#77 FND-981: adaEmbed.start() on ready
  src/index.ejs
  src/index.ts
  src/services/constructURL.ts
Labels: size/M

#78 FND-981: adaEmbed.start() on ready
  src/index.ejs
  src/index.ts
  src/services/constructURL.ts
Labels: size/M

#79 FND-999: Prevent mask clobbering
  src/components/App/Drawer/style.scss
Labels: size/XS

#81 FND-999: Prevent mask clobbering
  src/components/App/Drawer/style.scss
Labels: size/XS

#82 FND-980: Prevent multiple start/stop calls
  src/index.ejs
  src/index.ts
Labels: size/S

#83 FND-980: Prevent multiple start/stop calls
  src/index.ejs
  src/index.ts
Labels: size/S

#84 FND-1002: Quick fix change to CircleCI
  .circleci/config.yml
  package.json
  preact-hotfix.config.js
Labels: size/M

#80 FND-984: Fixes SVG blinking while it loads
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
Labels: size/S

#86 FND-992: IE Support for Custom Events
  src/index.ejs
  src/index.ts
  src/services/customEventPolyfill.ts
Labels: size/M

#85 FND-1006: Fixes default lang for intros URL
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
  src/services/translation.ts
Labels: size/S

#87 FND-984, FND-992, FND-1006
  .circleci/config.yml
  package.json
  preact-hotfix.config.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/index.ts
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
  src/services/customEventPolyfill.ts
  src/services/translation.ts
Labels: size/L

#88 Inject styles thru <style> tag instead of link with blob:
  package.json
  parent.config.js
  preact-hotfix.config.js
  preact.config.js
  yarn.lock
Labels: size/XL
