Repository AdaSupport/embed, pull requests merged in 2019-02, with the labels that each got.

#40 FND-861: Metafields bug fix on Mobile
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/M

#42 FND-856: Make mask overlay configurable
  PULL_REQUEST_TEMPLATE.md
  src/components/App/Drawer/index.test.js
  src/components/App/Drawer/index.tsx
  src/components/App/index.tsx
  src/index.ejs
Labels: size/M

#43 Merge Beta into Master
  PULL_REQUEST_TEMPLATE.md
  src/components/App/Drawer/index.test.js
  src/components/App/Drawer/index.tsx
  src/components/App/index.tsx
  src/index.ejs
Labels: size/M

#44 FND-862: Follow Up Responses for Mobile
  src/components/App/Drawer/index.tsx
  src/components/App/IFrame/index.tsx
  src/components/App/index.tsx
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/M

#45 FND-862: Follow Up Responses for Mobile
  src/components/App/Drawer/index.tsx
  src/components/App/IFrame/index.tsx
  src/components/App/index.tsx
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/L

#46 FND-875: Set meta fields in the Chat URL
  src/components/App/IFrame/index.tsx
  src/components/App/index.tsx
  src/index.ejs
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/M

#47 FND-874: Deprecate "greetingHandle" for "greeting"
  src/components/App/IFrame/index.tsx
  src/components/App/index.tsx
  src/index.ejs
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/M

#48 FND-874, FND-875
  src/components/App/IFrame/index.tsx
  src/components/App/index.tsx
  src/index.ejs
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/L

#18 Match Client Branding
  package.json
  src/components/App/Button/__snapshots__/index.test.js.snap
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/Drawer/__snapshots__/index.test.js.snap
  src/components/App/Drawer/index.test.js
  src/components/App/IFrame/index.test.js
  src/components/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/IntroBlurb/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/models/Client.ts
Labels: size/M

#51 FND-898, FND-900: Toggle Fix & Make Mobile Overlay on by Default
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/index.ejs
Labels: size/S

#50 FND-891, FND-898, FND-900
  package.json
  src/components/App/Button/__snapshots__/index.test.js.snap
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/Drawer/__snapshots__/index.test.js.snap
  src/components/App/Drawer/index.test.js
  src/components/App/IFrame/index.test.js
  src/components/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/IntroBlurb/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/index.ejs
  src/models/Client.ts
Labels: size/L

#54 HOTFIX: Zendesk Blink
  src/components/App/index.tsx
  src/index.ts
  src/services/zendesk.ts
Labels: size/S

#55 HOTFIX: Zendesk Blink
  src/components/App/index.tsx
  src/index.ts
  src/services/zendesk.ts
Labels: size/S

#49 EX-1161: Notification Badge for Embed
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
  src/style/utilities/colors.scss
  yarn.lock
Labels: size/L

#56 Notification Badge Feature
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.test.js
  src/components/App/index.tsx
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
  src/style/utilities/colors.scss
  yarn.lock
Labels: size/L

#52 FND-819, FND-904: Overlay and Intros Improvements
  src/components/App/IntroBlurb/style.scss
  src/components/App/index.tsx
  src/index.ejs
Labels: size/S

#58 HOTFIX: custom events
  src/components/App/Button/index.tsx
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/index.ejs
Labels: size/L

#59 HOTFIX: custom events
  src/components/App/Button/index.tsx
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/index.ejs
Labels: size/L

#53 FND-889: CATO Test and minor fixes
  src/components/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/IntroBlurb/style.scss
  src/components/App/index.tsx
Labels: size/M
