Repository AdaSupport/embed, pull requests merged in 2019-05, with the labels that each got.

#92 HOTFIX: Add cluster to connector URL
  src/components/App/index.tsx
Labels: size/XS

#91 INT-319: Introduce Drag and Drop to Embed
  src/components/App/Button/__snapshots__/index.test.js.snap
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/Draggable/index.tsx
  src/components/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/IntroBlurb/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/constants/configuration.ts
  src/index.ejs
  src/services/a11y.ts
  src/services/browsers.ts
Labels: size/L

#93 INT-319: Introduce Drag and Drop to Embed + ConnectorURL Fix
  .github/CODEOWNERS
  src/components/App/Button/__snapshots__/index.test.js.snap
  src/components/App/Button/index.test.js
  src/components/App/Button/index.tsx
  src/components/App/Button/style.scss
  src/components/App/Draggable/index.tsx
  src/components/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/IntroBlurb/style.scss
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/constants/configuration.ts
  src/index.ejs
  src/services/a11y.ts
  src/services/browsers.ts
Labels: size/XXL

#94 MEAS-426: Web interactions: send intro and url info to chatter endpoint
  src/components/App/Drawer/index.tsx
  src/components/App/IFrame/index.tsx
  src/components/App/IntroBlurb/index.test.js
  src/components/App/IntroBlurb/index.tsx
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
Labels: size/S

#97 Bm lock only on mobile
  package.json
  src/components/App/index.tsx
  yarn.lock
Labels: size/M

#101 MEAS-445: Make chatURL a dynamic getter. Send introShown param
  src/components/App/IFrame/index.tsx
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/services/constructURL.ts
Labels: size/M

#102 Release beta
  src/components/App/IFrame/index.tsx
  src/components/App/__snapshots__/index.test.js.snap
  src/components/App/index.tsx
  src/services/constructURL.ts
Labels: size/M

#104 FND-1157: Use AWS for staging embed
  .env.example
  README.md
  config/parent.config.js
  config/preact-beta.config.js
  config/preact-hotfix.config.js
  config/preact-static.config.js
  config/preact.config.js
  config/staging.config.js
  package.json
  parent.config.js
  src/index.ejs
Labels: size/L

#109 FND-1181: Be able to point to different clusters/bots when testing
  README.md
  src/index.ts
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/S

#111 Release changeable domain
  README.md
  src/index.ts
  src/services/__tests__/constructURL.test.js
  src/services/constructURL.ts
Labels: size/S

#112 Configurable Host Domain.
  src/components/App/index.tsx
Labels: size/XS

#106 FND-912: New implementation of reset action
  jest.config.js
  src/components/App/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/Button/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/Button/index.test.js
  src/components/AppWrapper/App/Button/index.tsx
  src/components/AppWrapper/App/Button/style.scss
  src/components/AppWrapper/App/Draggable/index.tsx
  src/components/AppWrapper/App/Drawer/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/Drawer/index.test.js
  src/components/AppWrapper/App/Drawer/index.tsx
  src/components/AppWrapper/App/Drawer/style.scss
  src/components/AppWrapper/App/IFrame/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/IFrame/index.test.js
  src/components/AppWrapper/App/IFrame/index.tsx
  src/components/AppWrapper/App/IFrame/style.scss
  src/components/AppWrapper/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/IntroBlurb/index.test.js
  src/components/AppWrapper/App/IntroBlurb/index.tsx
  src/components/AppWrapper/App/IntroBlurb/style.scss
  src/components/AppWrapper/App/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/index.test.js
  src/components/AppWrapper/App/index.tsx
  src/components/AppWrapper/App/style.scss
  src/components/AppWrapper/index.tsx
  src/index.ejs
  src/index.ts
  src/services/constructURL.ts
  tsconfig.json
  yarn.lock
Labels: size/L

#116 FND-1119: Intro Tabbing Fix
  src/components/AppWrapper/App/IntroBlurb/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/IntroBlurb/index.test.js
  src/components/AppWrapper/App/IntroBlurb/index.tsx
  src/index.ejs
Labels: size/S
