Repository AdaSupport/embed, pull requests merged in 2019-07, with the labels that each got.

#128 EM-19, EM-20: Add new getInfo properties
  src/components/AppWrapper/App/index.test.js
  src/components/AppWrapper/App/index.tsx
  src/components/AppWrapper/index.tsx
Labels: size/L

#129 Add new getInfo properties
  src/components/AppWrapper/App/index.test.js
  src/components/AppWrapper/App/index.tsx
  src/components/AppWrapper/index.tsx
Labels: size/L

#121 FND-1210: Save page scroll position on mobile
  src/components/AppWrapper/App/Drawer/index.tsx
  src/components/AppWrapper/App/index.tsx
Labels: size/M

#130 FND-1210: Save page scroll position on mobile
  src/components/AppWrapper/App/Drawer/index.tsx
  src/components/AppWrapper/App/index.tsx
Labels: size/M

#133 EM-34: Fix notification bubble on Firefox
  src/components/AppWrapper/App/Button/index.tsx
  src/components/AppWrapper/App/Button/style.scss
Labels: size/M

#134 Fix notification bubble on Firefox
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/AppWrapper/App/Button/index.tsx
  src/components/AppWrapper/App/Button/style.scss
Labels: size/M

#135 EM-43: Add allowFullScreen attribute to iframe
  src/components/AppWrapper/App/IFrame/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/IFrame/index.test.js
  src/components/AppWrapper/App/IFrame/index.tsx
Labels: size/XS

#136 EM-43: Add allowFullScreen attribute to iframe
  src/components/AppWrapper/App/IFrame/__snapshots__/index.test.js.snap
  src/components/AppWrapper/App/IFrame/index.test.js
  src/components/AppWrapper/App/IFrame/index.tsx
Labels: size/XS
