Repository AdaSupport/embed, pull requests merged in 2019-06, with the labels that each got.

#119 FND-1421: Fix to adaReadyCallback
  src/components/AppWrapper/App/index.test.js
  src/components/AppWrapper/App/index.tsx
  src/index.ejs
Labels: size/S

#120 FND-1421
  src/components/AppWrapper/App/index.test.js
  src/components/AppWrapper/App/index.tsx
  src/index.ejs
Labels: size/M

#122 kill IE9 and dance on its grave
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#124 Security Improvements
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  yarn.lock
Labels: size/M

#123 EM-3: Add a new "getInfo" method to Embed
  src/components/AppWrapper/App/index.tsx
  src/constants/events.ts
  src/index.ts
Labels: size/L

#126 Adds new `getInfo` functionality
  src/components/AppWrapper/App/index.tsx
  src/constants/events.ts
  src/index.ts
Labels: size/L
